name: eye_care_for_all
description: Eye Care For All
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.247.0+247

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_secure_storage: ^8.0.0
  dio: ^5.3.2
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.8
  google_fonts: any
  dartz: ^0.10.1
  permission_handler: ^11.1.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  intl: any
  connectivity_plus: ^4.0.2
  dotted_border: ^2.0.0+3
  carousel_slider: ^4.2.1
  camera: ^0.10.5+9
  url_launcher: ^6.1.12
  jwt_decoder: ^2.0.1
  screen_brightness: ^0.2.2+1
  logger: ^2.0.2
  flutter_native_splash: ^2.3.2
  speech_to_text: ^6.3.0
  avatar_glow: ^2.0.2
  animate_do: ^3.3.4
  flutter_launcher_icons: ^0.13.1
  uuid: ^3.0.7
  image_cropper: ^5.0.1
  photo_view: ^0.14.0
  feedback: ^3.1.0
  path: ^1.8.3
  fluttertoast: ^8.2.2
  package_info_plus: ^5.0.1
  flutter_jailbreak_detection: ^1.10.0
  easy_stepper: ^0.8.3
  pie_chart: ^5.4.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  matomo_tracker: ^4.1.1
  location: ^5.0.3
  flutter_verification_code: ^1.1.7
  another_stepper: ^1.2.2
  qr_flutter: ^4.1.0
  google_mlkit_face_mesh_detection: ^0.0.2
  google_mlkit_face_detection: ^0.9.0
  envied: ^0.5.3
  auto_size_text: ^3.0.0
  web_socket_channel: ^2.4.0
  date_picker_timeline: ^1.2.5
  stomp_dart_client: ^1.0.3
  gauge_indicator: ^0.4.3
  # in_app_update: ^4.2.2
  upgrader: ^9.0.0
  geocoding: ^3.0.0
  go_router: ^14.2.1
  # app_settings: ^5.1.1
  flutter_email_sender: ^6.0.3
  wolt_modal_sheet: ^0.8.0
  timelines: ^0.1.0

  flutter_miniapp_web_runner:
    path: packages/flutter_miniapp_web_runner/
  superapp_scanner:
    path: packages/superapp_scanner/
  dynamic_form:
    path : packages/dynamic_form/  

  pinput: ^4.0.0
  image_picker: ^1.0.7
  image: ^4.1.3
  path_provider: ^2.1.1

  password_generator: ^1.0.0
  sqflite_sqlcipher: ^2.2.1
  sqflite: ^2.3.0
  flutter_tts: ^3.8.5
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  workmanager: ^0.5.2
  fl_chart: ^0.68.0
  infinite_scroll_pagination: ^4.0.0
  font_awesome_flutter: ^10.7.0

  

# dependency_overrides:
#   camera:
#     git:
#       url: https://github.com/bottlepay/plugins.git
#       path: packages/camera/camera
#       ref: e1a4dba770da9bc3cf9f858bac6837083f8b9059

  flutter_riverpod: any
  collection: any
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  envied_generator: ^0.5.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/drawer_icons/
    - assets/nav_icons/
    - assets/images/animation_up.gif
    - assets/local_json/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
