enum EBCaseStatus {
  PENDING,
  COMPLETED,
  IN_PROGRESS,
  CANCELLED,
  UNKNOWN,
}

enum EBAssessmentName {
  INTIMATION,
  PRELIMINARY_SCREENING,
  CORNEA_RECOVERY,
  SHIPPED_TO_EYEBANK,
  RECEIVED_TO_EYEBANK,
  SEROLOGY,
  CORNEA_EVALUATION,
  IN_INVENTORY,
  UNKNOWN,

  // ONLY FOR TESTING
  ISSUE_ACQUISITION,
  ADVERSE_REACTION_REPORT,
  DOCTOR_ASSESSMENT,
}
