 /*
 * Copyright 2024 Infosys Ltd.
 * Use of this source code is governed by Apache License 2.0 that can be found in the LICENSE file or at
 * http://www.apache.org/licenses/LICENSE-2.0
 */

enum GoalOutcome {
    GLASSES_PRESCRIBED,
    OP_CONSULTATION,
    MEDICINE_PRESCRIBED,
    UNDER_OBSERVATION,
    ADMITTED,
    SURGERY_RECOMMENDED,
    REFERRED_TO_SPECIALIST,
    PATIENT_DID_NOT_VISIT,
    PATIENT_VISITED_OTHER_CLINIC,
    PATIENT_NOT_INTERESTED_IN_TREATMENT,
    TREATMENT_PLAN_PRESCRIBED,
    VISION_THERAPY_RECOMMENDED,
    REFERRAL_FOR_DIAGNOSTIC_TESTING,
    LOW_VISION_REHABILITATION,
    EDUCATION_AND_COUNSELING,
}
