name: dynamic_form
description: "A new Flutter package project."
version: 0.0.1


environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Logging
  logger: ^2.0.2

  # For Form Builder
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1

  # For State Management
  flutter_hooks: ^0.20.5

  # For Image Picker and File Picker
  file_picker:
  image_picker: ^1.1.2

  # For Decorations
  dotted_border: ^2.1.0

  # For Date Format
  intl: ^0.19.0

  # THIS IS FOR FILE UPLOAD TO CLOUDINARY
  dio: ^5.6.0
  
  # THIS IS FOR PDF VIEWER
  flutter_pdfview: any
  flutter_cache_manager: any
  path_provider: any
  path: any
  uuid: ^3.0.7
  expressions: ^0.2.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
    # - assets/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
