name: Build AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'

      - name: Flutter clean
        run: flutter clean
      
      - name: Install Dependencies
        run: flutter pub get

      - name: build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Decode android/upload-keystore.jks
        run: echo "${{ secrets.JKS_UPLOAD_SECRET }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Decode android/key.properties
        run: echo "${{ secrets.KEY_PROPERTIES_PROD }}" | base64 --decode > android/key.properties

      - name: Build APPBUNDLE
        run: flutter build appbundle --release --build-number ${{ github.run_number }}
      - name: Build Android APK
        run: flutter build apk --release --build-number ${{ github.run_number }}
      
      - name: Copy the file
        run: cp ./build/app/outputs/flutter-apk/app-release.apk ./build/app/outputs/flutter-apk/app-release-${{ github.run_number }}.apk

      - name: upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: stg-radar-mobility/eyecare4all
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Collaborators
          file: ./build/app/outputs/flutter-apk/app-release-${{ github.run_number }}.apk
          notifyTesters: true
          debug: false

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: apk-output
          path: ./build/app/outputs/bundle/release/app-release.aab
          retention-days: 10

          
